logging:
  level:
    cn:
      rui0:
        app: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?useUnicode=yes&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
    jedis:
          pool:
            # 最大空闲连接数
            max-idle: 500
            # 最小空闲连接数
            min-idle: 50
            # 等待可用连接的最大时间，负数为不限制
            max-wait:  -1s
            # 最大活跃连接数，负数为不限制
            max-active: -1
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: true

  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8088